/*
 * @Autor: huasenjio
 * @Date: 2022-10-22 10:49:51
 * @LastEditors: huasenjio
 * @LastEditTime: 2023-04-29 17:57:23
 * @Description:
 */

import Mock from 'mockjs2';
import { get, post } from '../request.js';

const findJournal = post('/journal/findAll', [
  {
    _id: '641881fa39ede6001dacb8b9',
    name: '默认订阅',
    expand: '{}',
    code: 0,
  },
]);
const findJournalInformationById = post('/journal/findJournalInformationById', {
  _id: '641881fa39ede6001dacb8b9',
  name: '默认订阅',
  code: 0,
  expand: '{}',
  series: [
    {
      typeName: '实用·工具',
      sites: [
        {
          _id: '6418821e39ede6001dacb8ba',
          name: '改图神器',
          url: 'https://img.logosc.cn/',
          icon: 'huasen-store/icon/1680024055278.png',
          code: 0,
          expand: '{}',
          description: '万能图片编辑器',
          remarks: '',
          describe: '万能图片编辑器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8bb',
          name: '二维码制作',
          url: 'https://www.qrdream.com/',
          icon: 'huasen-store/icon/1666499008478.png',
          code: 0,
          expand: '{}',
          description: '免费制作生成二维码的网站',
          remarks: '',
          describe: '免费制作生成二维码的网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8bc',
          name: '熊猫缩图',
          url: 'https://tinypng.com/',
          icon: 'huasen-store/icon/1681626525107.png',
          code: 0,
          expand: '{}',
          description: '在线图片压缩工具',
          remarks: '',
          describe: '在线图片压缩工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8bd',
          name: '错别字检测提示',
          url: 'http://www.biezi.com/',
          icon: 'huasen-store/icon/1680024080108.png',
          code: 0,
          expand: '{}',
          description: '在线自动检测错别字工具',
          remarks: '',
          describe: '在线自动检测错别字工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8be',
          name: '白描网页版',
          url: 'https://web.baimiaoapp.com/',
          icon: 'huasen-store/icon/1666499391628.png',
          code: 0,
          expand: '{}',
          description: '灵动的扫描识别神器',
          remarks: '',
          describe: '灵动的扫描识别神器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8bf',
          name: '顽固狗加密',
          url: 'https://www.dogged.cn/',
          icon: 'huasen-store/icon/1666500180472.png',
          code: 0,
          expand: '{}',
          description: '支持多种格式的在线文件加密网站',
          remarks: '',
          describe: '支持多种格式的在线文件加密网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c0',
          name: '流程图画板',
          url: 'https://excalidraw.com/',
          icon: 'huasen-store/icon/1680024109299.png',
          code: 0,
          expand: '{}',
          description: '在线手绘流程图画板',
          remarks: '',
          describe: '在线手绘流程图画板',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c1',
          name: '在线工具箱',
          url: 'http://www.atoolbox.net/',
          icon: 'huasen-store/icon/1666504581222.png',
          code: 0,
          expand: '{}',
          description: '好用丰富的在线工具箱',
          remarks: '',
          describe: '好用丰富的在线工具箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c2',
          name: '翻页时钟',
          url: 'http://a.huasen.cc/server/public/app/flip-clock/index.html',
          icon: 'huasen-store/icon/1680024140938.png',
          code: 0,
          expand: '{}',
          description: '在线桌面翻页时钟',
          remarks: '',
          describe: '在线桌面翻页时钟',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c3',
          name: '在线白板',
          url: 'http://tool.mkblog.cn/whiteboard/',
          icon: 'huasen-store/icon/1666505030295.png',
          code: 0,
          expand: '{}',
          description: '在线高颜值的支持压感的白板',
          remarks: '',
          describe: '在线高颜值的支持压感的白板',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c4',
          name: '秘塔写作猫',
          url: 'https://xiezuocat.com/#/',
          icon: 'huasen-store/icon/1666509024548.png',
          code: 0,
          expand: '{}',
          description: '在线辅助写作网站',
          remarks: '',
          describe: '在线辅助写作网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c5',
          name: '英语写作辅助',
          url: 'http://aimwriting.mtutor.engkoo.com/',
          icon: 'huasen-store/icon/1666509056764.png',
          code: 0,
          expand: '{}',
          description: '在线英语写作语法纠正平台',
          remarks: '',
          describe: '在线英语写作语法纠正平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c6',
          name: 'PDF工具',
          url: 'https://www.pdf2go.com/zh',
          icon: 'huasen-store/icon/1680022535100.png',
          code: 0,
          expand: '{}',
          description: '在线PDF编辑网站',
          remarks: '',
          describe: '在线PDF编辑网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c7',
          name: '即时工具',
          url: 'https://www.67tool.com/',
          icon: 'huasen-store/icon/1680113214816.png',
          code: 0,
          expand: '{}',
          description: '安全/快捷/好用的工具箱',
          remarks: '',
          describe: '安全/快捷/好用的工具箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c8',
          name: '123APP',
          url: 'https://123apps.com/cn/',
          icon: 'huasen-store/icon/1679938024630.png',
          code: 0,
          expand: '{}',
          description: '支持处理音频/PDF的多功能工具箱',
          remarks: '',
          describe: '支持处理音频/PDF的多功能工具箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8c9',
          name: '在线录屏',
          url: 'https://toolwa.com/record/',
          icon: 'huasen-store/icon/1666500097014.png',
          code: 0,
          expand: '{}',
          description: '无需安装的在线录屏网站',
          remarks: '',
          describe: '无需安装的在线录屏网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ca',
          name: '腾讯会议',
          url: 'https://meeting.tencent.com/',
          icon: 'huasen-store/icon/1670161932320.png',
          code: 0,
          expand: '{}',
          description: '随时随地开启在线会议',
          remarks: '',
          describe: '随时随地开启在线会议',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8cc',
          name: '拓展搜搜',
          url: 'https://www.crxsoso.com/',
          icon: 'huasen-store/icon/1671981830270.png',
          code: 0,
          expand: '{}',
          description: '免费下载浏览器插件的神器',
          remarks: '',
          describe: '免费下载浏览器插件的神器',
          remark: '',
        },
      ],
    },
    {
      typeName: '文艺·试听',
      sites: [
        {
          _id: '6418821e39ede6001dacb8cd',
          name: '网易云',
          url: 'https://music.163.com/',
          icon: 'huasen-store/icon/1666507242478.png',
          code: 0,
          expand: '{}',
          description: '专注于发现与分享的音乐平台',
          remarks: '',
          describe: '专注于发现与分享的音乐平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ce',
          name: 'QQ音乐',
          url: 'https://y.qq.com/',
          icon: 'huasen-store/icon/1666507321938.png',
          code: 0,
          expand: '{}',
          description: '海量版权的网络音乐服务产品',
          remarks: '',
          describe: '海量版权的网络音乐服务产品',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8cf',
          name: '电影狗',
          url: 'https://www.dianyinggou.com/yingku/',
          icon: 'huasen-store/icon/1666507697404.png',
          code: 0,
          expand: '{}',
          description: '影视资源搜索引擎',
          remarks: '',
          describe: '影视资源搜索引擎',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d0',
          name: '电影猫推荐',
          url: 'https://www.mvcat.com/',
          icon: 'huasen-store/icon/1682699600461.png',
          code: 0,
          expand: '{}',
          description: '专业的影视推荐平台',
          remarks: '',
          describe: '专业的影视推荐平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d1',
          name: '此刻',
          url: 'https://www.cikeee.com/',
          icon: 'huasen-store/icon/1666507800607.png',
          code: 0,
          expand: '{}',
          description: '每天推荐一部优秀电影',
          remarks: '',
          describe: '每天推荐一部优秀电影',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d2',
          name: '哔哩哔哩',
          url: 'https://www.bilibili.com/',
          icon: 'huasen-store/icon/1666507825660.png',
          code: 0,
          expand: '{}',
          description: '国内知名的视频弹幕网站',
          remarks: '',
          describe: '国内知名的视频弹幕网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d3',
          name: '腾讯视频',
          url: 'https://v.qq.com/',
          icon: 'huasen-store/icon/1666507869718.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d4',
          name: '爱奇艺',
          url: 'https://www.iqiyi.com/',
          icon: 'huasen-store/icon/1680334232504.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d5',
          name: '优酷',
          url: 'https://movie.youku.com/',
          icon: 'huasen-store/icon/1666507972726.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d6',
          name: '虎牙直播',
          url: 'https://www.huya.com/',
          icon: 'huasen-store/icon/1666507985744.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d7',
          name: '斗鱼直播',
          url: 'https://www.douyu.com/',
          icon: 'huasen-store/icon/1666508003156.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d9',
          name: '豆瓣FM',
          url: 'https://douban.fm/',
          icon: 'huasen-store/icon/1666508066362.png',
          code: 0,
          expand: '{}',
          description: '发现你的私属好音乐',
          remarks: '',
          describe: '发现你的私属好音乐',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8da',
          name: '荔枝FM',
          url: 'https://www.lizhi.fm/',
          icon: 'huasen-store/icon/1666508090010.png',
          code: 0,
          expand: '{}',
          description: '有声小说/相声/评书/脱口秀/广播剧/听书',
          remarks: '',
          describe: '有声小说/相声/评书/脱口秀/广播剧/听书',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8db',
          name: '喜马拉雅',
          url: 'https://www.ximalaya.com/',
          icon: 'huasen-store/icon/1680280931377.png',
          code: 0,
          expand: '{}',
          description: '为您找到每一天的精神食粮',
          remarks: '',
          describe: '为您找到每一天的精神食粮',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8dc',
          name: '茶杯狐',
          url: 'https://cupfox.app/',
          icon: 'huasen-store/icon/1680018418003.png',
          code: 0,
          expand: '{}',
          description: '努力让找电影变得简单',
          remarks: '',
          describe: '努力让找电影变得简单',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8dd',
          name: '耳聆网',
          url: 'https://www.ear0.com/',
          icon: 'huasen-store/icon/1680281008014.png',
          code: 0,
          expand: '{}',
          description: '音效爱好者的声音分享下载平台',
          remarks: '',
          describe: '音效爱好者的声音分享下载平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8de',
          name: '抖音',
          url: 'https://www.douyin.com/',
          icon: 'huasen-store/icon/1671975226761.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
    {
      typeName: '翻译·笔记',
      sites: [
        {
          _id: '6418821e39ede6001dacb8df',
          name: '有道翻译',
          url: 'https://fanyi.youdao.com/index.html',
          icon: 'huasen-store/icon/1671333942821.png',
          code: 0,
          expand: '{}',
          description: '网易旗下支持整个文档翻译工具',
          remarks: '',
          describe: '网易旗下支持整个文档翻译工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e0',
          name: '百度翻译',
          url: 'https://fanyi.baidu.com/',
          icon: 'huasen-store/icon/1671334170363.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e1',
          name: '火山翻译',
          url: 'https://translate.volcengine.com/translate',
          icon: 'huasen-store/icon/1671334266195.png',
          code: 0,
          expand: '{}',
          description: '字节跳动出品的翻译工具',
          remarks: '',
          describe: '字节跳动出品的翻译工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e2',
          name: 'Deepl翻译器',
          url: 'https://www.deepl.com/translator',
          icon: 'huasen-store/icon/1666504639003.png',
          code: 0,
          expand: '{}',
          description: '支持即时翻译文本的专业翻译器',
          remarks: '',
          describe: '支持即时翻译文本的专业翻译器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e3',
          name: 'Fsou翻译',
          url: 'https://fsoufsou.com/translate',
          icon: 'huasen-store/icon/1671950668786.png',
          code: 0,
          expand: '{}',
          description: '小众简洁的翻译网站',
          remarks: '',
          describe: '小众简洁的翻译网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e4',
          name: 'Notion',
          url: 'https://www.notion.so/product',
          icon: 'huasen-store/icon/1666508612962.png',
          code: 0,
          expand: '{}',
          description: '专业的笔记网站',
          remarks: '',
          describe: '专业的笔记网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e5',
          name: '幕布笔记',
          url: 'https://mubu.com/',
          icon: 'huasen-store/icon/1666508598862.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e6',
          name: '印象笔记',
          url: 'https://www.yinxiang.com/',
          icon: 'huasen-store/icon/1680281137055.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e7',
          name: '有道笔记',
          url: 'https://note.youdao.com/web/',
          icon: 'huasen-store/icon/1666508552279.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e8',
          name: 'FlowUs',
          url: 'https://flowus.cn/product',
          icon: 'huasen-store/icon/1680281536858.png',
          code: 0,
          expand: '{}',
          description: '新一代知识管理与协作平台',
          remarks: '',
          describe: '新一代知识管理与协作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8e9',
          name: '我来',
          url: 'https://www.wolai.com/',
          icon: 'huasen-store/icon/1671335463081.png',
          code: 0,
          expand: '{}',
          description: '多人编辑便捷协同的笔记工具',
          remarks: '',
          describe: '多人编辑便捷协同的笔记工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ea',
          name: '雀语',
          url: 'https://www.yuque.com/',
          icon: 'huasen-store/icon/1671336310359.png',
          code: 0,
          expand: '{}',
          description: '提供优秀的文档与知识库工具',
          remarks: '',
          describe: '提供优秀的文档与知识库工具',
          remark: '',
        },
      ],
    },
    {
      typeName: '新闻·资讯',
      sites: [
        {
          _id: '6418821e39ede6001dacb8eb',
          name: '后续',
          url: 'https://houxu.app/',
          icon: 'huasen-store/icon/1671962810607.png',
          code: 0,
          expand: '{}',
          description: '万事皆有后续',
          remarks: '',
          describe: '万事皆有后续',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ec',
          name: 'TheTop',
          url: 'https://the.top/',
          icon: 'huasen-store/icon/1666508190229.png',
          code: 0,
          expand: '{}',
          description: '每日热点资讯排行榜',
          remarks: '',
          describe: '每日热点资讯排行榜',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ed',
          name: '雷峰网',
          url: 'https://www.leiphone.com/',
          icon: 'huasen-store/icon/1666508224622.png',
          code: 0,
          expand: '{}',
          description: '具有代表性的实力型科技新媒体与信息服务平台',
          remarks: '',
          describe: '具有代表性的实力型科技新媒体与信息服务平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ee',
          name: '网易数读',
          url: 'https://data.163.com/',
          icon: 'huasen-store/icon/1666508249547.png',
          code: 0,
          expand: '{}',
          description: '数据图表说明热点问题',
          remarks: '',
          describe: '数据图表说明热点问题',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ef',
          name: '今日热榜',
          url: 'https://tophub.today/',
          icon: 'huasen-store/icon/1666508292010.png',
          code: 0,
          expand: '{}',
          description: '提供各站热榜聚合追踪全网热点',
          remarks: '',
          describe: '提供各站热榜聚合追踪全网热点',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f0',
          name: 'Readhub',
          url: 'https://readhub.cn/topics',
          icon: 'huasen-store/icon/1666508384522.png',
          code: 0,
          expand: '{}',
          description: '每天三分钟的科技新闻聚合阅读',
          remarks: '',
          describe: '每天三分钟的科技新闻聚合阅读',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f1',
          name: '虎嗅网',
          url: 'https://www.huxiu.com/',
          icon: 'huasen-store/icon/1666508405226.png',
          code: 0,
          expand: '{}',
          description: '不错过互联网的每个重要时刻',
          remarks: '',
          describe: '不错过互联网的每个重要时刻',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f2',
          name: '36kr',
          url: 'https://36kr.com/',
          icon: 'huasen-store/icon/1680282271770.png',
          code: 0,
          expand: '{}',
          description: '独家的视角为用户深度剖析最前沿的资讯',
          remarks: '',
          describe: '独家的视角为用户深度剖析最前沿的资讯',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f3',
          name: '巨潮资讯网',
          url: 'http://www.cninfo.com.cn/new/index',
          icon: 'huasen-store/icon/1671962884381.png',
          code: 0,
          expand: '{}',
          description: '为投资者提供一站式的证券市场信息服务',
          remarks: '',
          describe: '为投资者提供一站式的证券市场信息服务',
          remark: '',
        },
      ],
    },
    {
      typeName: '邮箱·脑图',
      sites: [
        {
          _id: '6418821e39ede6001dacb8f6',
          name: 'QQ邮箱',
          url: 'https://mail.qq.com/',
          icon: 'huasen-store/icon/1666508516456.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f7',
          name: '谷歌邮箱',
          url: 'https://www.google.com/intl/zh-CN_cn/gmail/about/',
          icon: 'huasen-store/icon/1666508530924.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f8',
          name: '临时邮箱',
          url: 'https://www.linshiyouxiang.net/',
          icon: 'huasen-store/icon/1666508797990.png',
          code: 0,
          expand: '{}',
          description: '免费完全匿名的临时邮箱',
          remarks: '',
          describe: '免费完全匿名的临时邮箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8f9',
          name: 'TempMail',
          url: 'https://temp-mail.org/zh/',
          icon: 'huasen-store/icon/1666508912080.png',
          code: 0,
          expand: '{}',
          description: '提供临时安全匿名免费的一次性电子邮件地址',
          remarks: '',
          describe: '提供临时安全匿名免费的一次性电子邮件地址',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8fa',
          name: '百度脑图',
          url: 'https://naotu.baidu.com/',
          icon: 'huasen-store/icon/1669216617181.png',
          code: 0,
          expand: '{}',
          description: '便捷的思维工具',
          remarks: '',
          describe: '便捷的思维工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8fb',
          name: 'ZhiMap',
          url: 'https://zhimap.com/',
          icon: 'huasen-store/icon/1671973024258.png',
          code: 0,
          expand: '{}',
          description: '完全免费的在线思维导图工具',
          remarks: '',
          describe: '完全免费的在线思维导图工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8fc',
          name: 'GitMind',
          url: 'https://gitmind.cn/',
          icon: 'huasen-store/icon/1671973109866.png',
          code: 0,
          expand: '{}',
          description: '新一代免费思维导图协作软件',
          remarks: '',
          describe: '新一代免费思维导图协作软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8fd',
          name: '知犀思维导图',
          url: 'https://www.zhixi.com/',
          icon: 'huasen-store/icon/1671974063387.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
    {
      typeName: '网盘·传输',
      sites: [
        {
          _id: '6418821e39ede6001dacb8fe',
          name: '阿里云盘',
          url: 'https://www.aliyundrive.com/',
          icon: 'huasen-store/icon/1671333047217.png',
          code: 0,
          expand: '{}',
          description: '快速安全的存储云盘',
          remarks: '',
          describe: '快速安全的存储云盘',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8ff',
          name: '百度云盘',
          url: 'https://pan.baidu.com/',
          icon: 'huasen-store/icon/1671333162886.png',
          code: 0,
          expand: '{}',
          description: '下载速度慢并且摆脱不掉的云盘',
          remarks: '',
          describe: '下载速度慢并且摆脱不掉的云盘',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb900',
          name: '腾讯微云',
          url: 'https://www.weiyun.com/',
          icon: 'huasen-store/icon/1671333256021.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb901',
          name: '城通云盘',
          url: 'https://www.ctfile.com/',
          icon: 'huasen-store/icon/1671333330812.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb902',
          name: '夸克云盘',
          url: 'https://pan.quark.cn/',
          icon: 'huasen-store/icon/1671333465760.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb903',
          name: '空投',
          url: 'https://airportal.cn/',
          icon: 'huasen-store/icon/1666504413567.png',
          code: 0,
          expand: '{}',
          description: '跨设备文件传输网站',
          remarks: '',
          describe: '跨设备文件传输网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb904',
          name: '牛奶快传',
          url: 'https://cowtransfer.com/',
          icon: 'huasen-store/icon/1666505530102.png',
          code: 0,
          expand: '{}',
          description: '在线大文件传输工具',
          remarks: '',
          describe: '在线大文件传输工具',
          remark: '',
        },
      ],
    },
    {
      typeName: '打开·眼界',
      sites: [
        {
          _id: '6418821e39ede6001dacb90c',
          name: '中国传统颜色',
          url: 'http://zhongguose.com/',
          icon: 'huasen-store/icon/1666512692063.png',
          code: 0,
          expand: '{}',
          description: '收集各种中国的传统颜色',
          remarks: '',
          describe: '收集各种中国的传统颜色',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb90d',
          name: '炫酷光绘',
          url: 'http://weavesilk.com/',
          icon: 'huasen-store/icon/1666513245745.png',
          code: 0,
          expand: '{}',
          description: '炫酷的对称光束生成网站',
          remarks: '',
          describe: '炫酷的对称光束生成网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb90e',
          name: 'Species',
          url: 'http://www.species-in-pieces.com/',
          icon: 'huasen-store/icon/1666513312132.png',
          code: 0,
          expand: '{}',
          description: '定时轮播濒危灭绝物种的抽象图片',
          remarks: '',
          describe: '定时轮播濒危灭绝物种的抽象图片',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb90f',
          name: 'StarsEmmision',
          url: 'https://wangyasai.github.io/Stars-Emmision/',
          icon: 'huasen-store/icon/1666513222614.png',
          code: 0,
          expand: '{}',
          description: '在线生成光束射线的网站',
          remarks: '',
          describe: '在线生成光束射线的网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb910',
          name: '纪妖',
          url: 'https://www.cbaigui.com/',
          icon: 'huasen-store/icon/1666510918488.png',
          code: 0,
          expand: '{}',
          description: '收集介绍中国古今传说的妖怪',
          remarks: '',
          describe: '收集介绍中国古今传说的妖怪',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb911',
          name: '全景故宫',
          url: 'https://pano.dpm.org.cn/',
          icon: 'huasen-store/icon/1666511029759.png',
          code: 0,
          expand: '{}',
          description: '360全景视感受故宫浑厚的文化',
          remarks: '',
          describe: '360全景视感受故宫浑厚的文化',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb912',
          name: '故宫博物馆',
          url: 'https://digicol.dpm.org.cn/',
          icon: 'huasen-store/icon/1666510941763.png',
          code: 0,
          expand: '{}',
          description: '故宫数字文物博物馆',
          remarks: '',
          describe: '故宫数字文物博物馆',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb913',
          name: '指尖上',
          url: 'https://www.zhijianshang.com/',
          icon: 'huasen-store/icon/1671962069512.png',
          code: 0,
          expand: '{}',
          description: '指尖上的全球360全景',
          remarks: '',
          describe: '指尖上的全球360全景',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb914',
          name: '全历史',
          url: 'https://www.allhistory.com/',
          icon: 'huasen-store/icon/1666510868728.png',
          code: 0,
          expand: '{}',
          description: '知识图谱为核心引擎多维度呈现历史知识',
          remarks: '',
          describe: '知识图谱为核心引擎多维度呈现历史知识',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb915',
          name: '译学馆',
          url: 'https://www.yxgapp.com/',
          icon: 'huasen-store/icon/1666510904487.png',
          code: 0,
          expand: '{}',
          description: '科普有趣的知识频道',
          remarks: '',
          describe: '科普有趣的知识频道',
          remark: '',
        },
      ],
    },
    {
      typeName: '文档·问卷',
      sites: [
        {
          _id: '6418821e39ede6001dacb905',
          name: '腾讯文档',
          url: 'https://docs.qq.com/',
          icon: 'huasen-store/icon/1666508727007.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb906',
          name: '石墨文档',
          url: 'https://shimo.im/',
          icon: 'huasen-store/icon/1666508746871.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb907',
          name: '金山文档',
          url: 'https://www.kdocs.cn/welcome',
          icon: 'huasen-store/icon/1666508767991.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb908',
          name: '飞书文档',
          url: 'https://www.feishu.cn/',
          icon: 'huasen-store/icon/1681137394411.png',
          code: 0,
          expand: '{}',
          description: '飞书全家福中专业的文档',
          remarks: '',
          describe: '飞书全家福中专业的文档',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb909',
          name: '腾讯问卷',
          url: 'https://wj.qq.com/',
          icon: 'huasen-store/icon/1681137428819.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb90a',
          name: '问卷星',
          url: 'https://www.wjx.cn/',
          icon: 'huasen-store/icon/1671336689961.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb90b',
          name: '问卷帮',
          url: 'https://www.wenjuanbang.com/',
          icon: 'huasen-store/icon/1671336782239.png',
          code: 0,
          expand: '{}',
          description: '免费的在线问卷工具',
          remarks: '',
          describe: '免费的在线问卷工具',
          remark: '',
        },
      ],
    },
    {
      typeName: '趣玩·一下',
      sites: [
        {
          _id: '6418821e39ede6001dacb916',
          name: '几枝',
          url: 'https://toolwa.com/jizhi/',
          icon: 'huasen-store/icon/1680282468591.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb917',
          name: 'Emoji合成',
          url: 'https://tikolu.net/emojimix/',
          icon: 'huasen-store/icon/1666513265884.png',
          code: 0,
          expand: '{}',
          description: '支持emoji图标融合制成新图标',
          remarks: '',
          describe: '支持emoji图标融合制成新图标',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb919',
          name: '云段子',
          url: 'http://www.yduanzi.com/',
          icon: 'huasen-store/icon/1666511434761.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb91b',
          name: '糖衣炮弹',
          url: 'http://www.seeprettyface.com/',
          icon: 'https://www.seeprettyface.com/favicon.ico',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb91c',
          name: '童年游戏机',
          url: 'http://lab.mkblog.cn/FCGames/#/',
          icon: 'https://mklab.eu.org/FCGames/favicon.ico',
          code: 0,
          expand: '{}',
          description: '免费在线FC小游戏',
          remarks: '',
          describe: '免费在线FC小游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb91d',
          name: '贪吃蛇',
          url: 'http://slither.io/',
          icon: 'huasen-store/icon/1666511501382.png',
          code: 0,
          expand: '{}',
          description: '在线联网贪吃蛇小游戏',
          remarks: '',
          describe: '在线联网贪吃蛇小游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb91e',
          name: '桌球',
          url: 'http://www.heyzxz.me/pcol/',
          icon: 'huasen-store/icon/1666511541687.png',
          code: 0,
          expand: '{}',
          description: '在线娱乐桌球游戏',
          remarks: '',
          describe: '在线娱乐桌球游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb91f',
          name: '单词游戏',
          url: 'https://zty.pe/',
          icon: 'huasen-store/icon/1666511564222.png',
          code: 0,
          expand: '{}',
          description: '边玩边记单词小游戏',
          remarks: '',
          describe: '边玩边记单词小游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb920',
          name: '蜂眼消消乐',
          url: 'https://hex.frvr.com/',
          icon: 'huasen-store/icon/1666511601624.png',
          code: 0,
          expand: '{}',
          description: '酷似消消乐的益智小游戏',
          remarks: '',
          describe: '酷似消消乐的益智小游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb921',
          name: '在线架子鼓',
          url: 'http://tool.mkblog.cn/durms/',
          icon: 'huasen-store/icon/1666511624567.png',
          code: 0,
          expand: '{}',
          description: '在线架子鼓打击乐器',
          remarks: '',
          describe: '在线架子鼓打击乐器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb922',
          name: '米粒小车',
          url: 'https://bruno-simon.com/',
          icon: 'huasen-store/icon/1666511823736.png',
          code: 0,
          expand: '{}',
          description: '模拟遥控操作小车',
          remarks: '',
          describe: '模拟遥控操作小车',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb923',
          name: '围捕小猫',
          url: 'http://a.huasen.cc/server/public/app/round-cat/index.html',
          icon: '',
          code: 0,
          expand: '{}',
          description: '圈住小猫的益智游戏',
          remarks: '',
          describe: '圈住小猫的益智游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb924',
          name: '荒庙逃亡',
          url: 'http://a.huasen.cc/server/public/app/temple-run/index.html',
          icon: '',
          code: 0,
          expand: '{}',
          description: '荒庙逃亡跑酷游戏',
          remarks: '',
          describe: '荒庙逃亡跑酷游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb925',
          name: '俄罗斯方块',
          url: 'http://a.huasen.cc/server/public/app/tetris/index.html',
          icon: '',
          code: 0,
          expand: '{}',
          description: '俄罗斯方块经典怀旧版',
          remarks: '',
          describe: '俄罗斯方块经典怀旧版',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb926',
          name: 'PlayLines',
          url: 'https://lines.frvr.com/',
          icon: 'huasen-store/icon/1666511892667.png',
          code: 0,
          expand: '{}',
          description: '相同颜色相连的益智小游戏',
          remarks: '',
          describe: '相同颜色相连的益智小游戏',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb927',
          name: '我的世界',
          url: 'https://classic.minecraft.net/',
          icon: 'huasen-store/icon/1666511457277.png',
          code: 0,
          expand: '{}',
          description: '我的游戏在线联机版本',
          remarks: '',
          describe: '我的游戏在线联机版本',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb928',
          name: '自由钢琴',
          url: 'https://www.autopiano.cn/',
          icon: 'huasen-store/icon/1666511396234.png',
          code: 0,
          expand: '{}',
          description: '支持在线弹奏钢琴',
          remarks: '',
          describe: '支持在线弹奏钢琴',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb929',
          name: '蝌蚪聊天室',
          url: 'http://kedou.workerman.net/',
          icon: 'huasen-store/icon/1666511664318.png',
          code: 0,
          expand: '{}',
          description: '即时通讯的小蝌蚪聊天室',
          remarks: '',
          describe: '即时通讯的小蝌蚪聊天室',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb92a',
          name: '在线电子音乐',
          url: 'https://learningmusic.ableton.com/zh-Hans/index.html',
          icon: 'huasen-store/icon/1666511688301.png',
          code: 0,
          expand: '{}',
          description: '在线开始音乐创作之旅',
          remarks: '',
          describe: '在线开始音乐创作之旅',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb92b',
          name: '电子木鱼',
          url: 'https://toolwa.com/wooden-fish/',
          icon: 'huasen-store/icon/1680282769504.png',
          code: 0,
          expand: '{}',
          description: '敲木鱼攒功德',
          remarks: '',
          describe: '敲木鱼攒功德',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb92c',
          name: '烟花模拟器',
          url: 'https://toolwa.com/firework/',
          icon: 'huasen-store/icon/1680282821040.png',
          code: 0,
          expand: '{}',
          description: '在线欣赏烟花的网站',
          remarks: '',
          describe: '在线欣赏烟花的网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb92d',
          name: '手鼓猫',
          url: 'https://toolwa.com/bongocat/',
          icon: 'huasen-store/icon/1680282849996.png',
          code: 0,
          expand: '{}',
          description: '可爱魔性的在线手鼓猫',
          remarks: '',
          describe: '可爱魔性的在线手鼓猫',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb92e',
          name: '飞机大战',
          url: 'https://mklab.eu.org/PlaneWars/',
          icon: '',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb92f',
          name: '快速涂鸦',
          url: 'https://quickdraw.withgoogle.com/',
          icon: '',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb8d8',
          name: '白噪音魔盒',
          url: 'http://a.huasen.cc/server/public/app/white-noise/index.html',
          icon: '',
          code: 0,
          expand: '{}',
          description: '混合场景发出白噪音助眠音乐',
          remarks: '',
          describe: '混合场景发出白噪音助眠音乐',
          remark: '',
        },
      ],
    },
    {
      typeName: '设计·工具',
      sites: [
        {
          _id: '6418821e39ede6001dacb930',
          name: '创客贴',
          url: 'https://www.chuangkit.com/designtools/startdesign',
          icon: 'huasen-store/icon/1666511962635.png',
          code: 0,
          expand: '{}',
          description: '专注图片模板在线设计',
          remarks: '',
          describe: '专注图片模板在线设计',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb931',
          name: '懒设计',
          url: 'https://www.fotor.com.cn/',
          icon: 'huasen-store/icon/1666511986045.png',
          code: 0,
          expand: '{}',
          description: '创意图文设计神器',
          remarks: '',
          describe: '创意图文设计神器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb932',
          name: 'AutoDraw',
          url: 'https://www.autodraw.com/',
          icon: 'huasen-store/icon/1666512307441.png',
          code: 0,
          expand: '{}',
          description: 'AI辅助涂鸦创作网站',
          remarks: '',
          describe: 'AI辅助涂鸦创作网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb933',
          name: '玛良动效',
          url: 'https://design.alipay.com/emotion',
          icon: 'huasen-store/icon/1666512349068.png',
          code: 0,
          expand: '{}',
          description: '一站式动效制作平台',
          remarks: '',
          describe: '一站式动效制作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb934',
          name: 'Coolbackgrounds',
          url: 'https://coolbackgrounds.io/',
          icon: 'huasen-store/icon/1671962989049.png',
          code: 0,
          expand: '{}',
          description: '炫酷背景图片生成器',
          remarks: '',
          describe: '炫酷背景图片生成器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb935',
          name: '炫酷光绘',
          url: 'http://weavesilk.com/',
          icon: 'huasen-store/icon/1666513245745.png',
          code: 0,
          expand: '{}',
          description: '炫酷的对称光束生成网站',
          remarks: '',
          describe: '炫酷的对称光束生成网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb936',
          name: '数码设备带壳图片制作',
          url: 'https://deviceshots.com/',
          icon: 'huasen-store/icon/1666512038742.png',
          code: 0,
          expand: '{}',
          description: '多端设备样机展示制作平台',
          remarks: '',
          describe: '多端设备样机展示制作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb937',
          name: '一帧秒创',
          url: 'https://aigc.yizhentv.com/',
          icon: 'huasen-store/icon/1671953657070.png',
          code: 0,
          expand: '{}',
          description: '智能图文创作平台',
          remarks: '',
          describe: '智能图文创作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb938',
          name: 'Geometrize',
          url: 'https://www.geometrize.co.uk/',
          icon: 'huasen-store/icon/1680282926441.png',
          code: 0,
          expand: '{}',
          description: '支持图片一键像素化',
          remarks: '',
          describe: '支持图片一键像素化',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb939',
          name: 'Blobmaker',
          url: 'https://www.blobmaker.app/',
          icon: 'huasen-store/icon/1680282954659.png',
          code: 0,
          expand: '{}',
          description: '支持一键生成不规则形状图片',
          remarks: '',
          describe: '支持一键生成不规则形状图片',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb93a',
          name: 'Petalica',
          url: 'https://petalica.com/',
          icon: '',
          code: 0,
          expand: '{}',
          description: '绘画稿智能上色网站',
          remarks: '',
          describe: '绘画稿智能上色网站',
          remark: '',
        },
      ],
    },
    {
      typeName: '创作·平台',
      sites: [
        {
          _id: '6418821e39ede6001dacb93b',
          name: '花瓣',
          url: 'https://huaban.com/',
          icon: 'huasen-store/icon/1666511922387.png',
          code: 0,
          expand: '{}',
          description: '陪你做生活的设计师',
          remarks: '',
          describe: '陪你做生活的设计师',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb93c',
          name: '站酷',
          url: 'https://www.zcool.com.cn/',
          icon: 'huasen-store/icon/1666511938311.png',
          code: 0,
          expand: '{}',
          description: '专业的设计创意互动平台',
          remarks: '',
          describe: '专业的设计创意互动平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb93d',
          name: '涂鸦王国',
          url: 'https://www.gracg.com/',
          icon: 'huasen-store/icon/1666511953054.png',
          code: 0,
          expand: '{}',
          description: '原创插画内容创作平台',
          remarks: '',
          describe: '原创插画内容创作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb93e',
          name: 'Designdaily',
          url: 'https://uidesigndaily.com/',
          icon: 'huasen-store/icon/1680283022294.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
    {
      typeName: '颜色·搭配',
      sites: [
        {
          _id: '6418821e39ede6001dacb93f',
          name: '中国传统颜色',
          url: 'http://zhongguose.com/',
          icon: 'huasen-store/icon/1666512692063.png',
          code: 0,
          expand: '{}',
          description: '收集各种中国的传统颜色',
          remarks: '',
          describe: '收集各种中国的传统颜色',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb940',
          name: '日本传统颜色',
          url: 'https://nipponcolors.com/',
          icon: 'huasen-store/icon/1671952834481.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb941',
          name: 'ColorHunt',
          url: 'https://colorhunt.co/',
          icon: 'huasen-store/icon/1666512704616.png',
          code: 0,
          expand: '{}',
          description: '设计师和艺术家的调色板',
          remarks: '',
          describe: '设计师和艺术家的调色板',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb942',
          name: 'ColorDrop',
          url: 'https://colordrop.io/',
          icon: 'huasen-store/icon/1666512730403.png',
          code: 0,
          expand: '{}',
          description: '颜色策划搭配方案神器',
          remarks: '',
          describe: '颜色策划搭配方案神器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb943',
          name: 'WebGradients',
          url: 'https://webgradients.com/',
          icon: 'huasen-store/icon/1666512753969.png',
          code: 0,
          expand: '{}',
          description: '线性渐变球体配色网站',
          remarks: '',
          describe: '线性渐变球体配色网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb944',
          name: 'Uigradients',
          url: 'https://uigradients.com/#Shore',
          icon: 'huasen-store/icon/1666512773766.png',
          code: 0,
          expand: '{}',
          description: '线性渐变背景配色网站',
          remarks: '',
          describe: '线性渐变背景配色网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb945',
          name: 'Gradient',
          url: 'https://gradient.shapefactory.co/',
          icon: 'huasen-store/icon/1666512797381.png',
          code: 0,
          expand: '{}',
          description: '可调节的渐变配色网站',
          remarks: '',
          describe: '可调节的渐变配色网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb946',
          name: 'AdobeColor',
          url: 'https://color.adobe.com/zh/create/color-wheel',
          icon: 'huasen-store/icon/1680283069793.png',
          code: 0,
          expand: '{}',
          description: '通过不同色彩规则来提供配色参考',
          remarks: '',
          describe: '通过不同色彩规则来提供配色参考',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb947',
          name: 'MyColorSpace',
          url: 'https://mycolor.space/',
          icon: 'huasen-store/icon/1677988687488.png',
          code: 0,
          expand: '{}',
          description: '支持选择颜色生成配色方案',
          remarks: '',
          describe: '支持选择颜色生成配色方案',
          remark: '',
        },
      ],
    },
    {
      typeName: '壁纸·图标',
      sites: [
        {
          _id: '6418821e39ede6001dacb948',
          name: '图虫',
          url: 'https://tuchong.com/explore/',
          icon: 'huasen-store/icon/1666512499998.png',
          code: 0,
          expand: '{}',
          description: '国内优秀摄影师交流社区',
          remarks: '',
          describe: '国内优秀摄影师交流社区',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb949',
          name: 'Pixabay',
          url: 'https://pixabay.com/photos/',
          icon: 'huasen-store/icon/1666512517116.png',
          code: 0,
          expand: '{}',
          description: '提供令人惊叹的免费库存照片下载平台',
          remarks: '',
          describe: '提供令人惊叹的免费库存照片下载平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb94a',
          name: 'StockSnap',
          url: 'https://stocksnap.io/',
          icon: 'huasen-store/icon/1666512576138.png',
          code: 0,
          expand: '{}',
          description: '汇聚千上万的无版权库存图片',
          remarks: '',
          describe: '汇聚千上万的无版权库存图片',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb94b',
          name: 'Wallhaven',
          url: 'https://wallhaven.cc/toplist',
          icon: 'huasen-store/icon/1666512602282.png',
          code: 0,
          expand: '{}',
          description: '资源丰富的壁纸网站',
          remarks: '',
          describe: '资源丰富的壁纸网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb94c',
          name: 'Pixivic',
          url: 'https://pixivic.com/?VNK=8cb3416c',
          icon: 'huasen-store/icon/1666512622872.png',
          code: 0,
          expand: '{}',
          description: '各类动漫二次元插画',
          remarks: '',
          describe: '各类动漫二次元插画',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb94d',
          name: 'Akspic',
          url: 'https://akspic.ru/',
          icon: 'huasen-store/icon/1666512633014.png',
          code: 0,
          expand: '{}',
          description: '高质量的壁纸免费下载平台',
          remarks: '',
          describe: '高质量的壁纸免费下载平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb94e',
          name: 'Unsplash',
          url: 'https://unsplash.com/',
          icon: 'huasen-store/icon/1666512655037.png',
          code: 0,
          expand: '{}',
          description: '免费优质的图片分享网站',
          remarks: '',
          describe: '免费优质的图片分享网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb94f',
          name: 'Iconfont',
          url: 'https://www.iconfont.cn/',
          icon: 'huasen-store/icon/1680194727553.png',
          code: 0,
          expand: '{}',
          description: '专业的矢量图标库',
          remarks: '',
          describe: '专业的矢量图标库',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb950',
          name: 'Iconstore',
          url: 'https://iconstore.co/',
          icon: 'huasen-store/icon/1680194750938.png',
          code: 0,
          expand: '{}',
          description: '可商用的免费图标库下载平台',
          remarks: '',
          describe: '可商用的免费图标库下载平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb951',
          name: 'FontAwesome5',
          url: 'https://fa5.dashgame.com/',
          icon: 'huasen-store/icon/1671248476232.png',
          code: 0,
          expand: '{}',
          description: '风靡全球的图标字体库',
          remarks: '',
          describe: '风靡全球的图标字体库',
          remark: '',
        },
      ],
    },
    {
      typeName: '媒体·编辑',
      sites: [
        {
          _id: '6418821e39ede6001dacb952',
          name: '网易见外工作台',
          url: 'https://jianwai.youdao.com/',
          icon: 'huasen-store/icon/1671358857257.png',
          code: 0,
          expand: '{}',
          description: 'AI智能语音转写听翻平台',
          remarks: '',
          describe: 'AI智能语音转写听翻平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb953',
          name: '蜜蜂剪辑',
          url: 'https://beecut.cn/online-video-editor',
          icon: 'huasen-store/icon/1666499264881.png',
          code: 0,
          expand: '{}',
          description: '在线音视频编辑工具',
          remarks: '',
          describe: '在线音视频编辑工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb954',
          name: '智影',
          url: 'https://zenvideo.qq.com/',
          icon: 'huasen-store/icon/1671379985550.png',
          code: 0,
          expand: '{}',
          description: '超好用在线智能创作平台',
          remarks: '',
          describe: '超好用在线智能创作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb955',
          name: '稿定图片',
          url: 'https://www.uupoop.com/',
          icon: 'huasen-store/icon/1666499833272.png',
          code: 0,
          expand: '{}',
          description: '在线制作编辑图片工具',
          remarks: '',
          describe: '在线制作编辑图片工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb956',
          name: 'Photopea',
          url: 'https://toolwa.com/ps/',
          icon: 'huasen-store/icon/1671380125603.png',
          code: 0,
          expand: '{}',
          description: '免费强大在线PS工具',
          remarks: '',
          describe: '免费强大在线PS工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb957',
          name: '图片去除背景',
          url: 'https://www.remove.bg/',
          icon: 'huasen-store/icon/1666499654383.png',
          code: 0,
          expand: '{}',
          description: '专业的图片背景去除工具',
          remarks: '',
          describe: '专业的图片背景去除工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb958',
          name: '视频去除背景',
          url: 'https://www.unscreen.com/',
          icon: 'huasen-store/icon/1666499746343.png',
          code: 0,
          expand: '{}',
          description: '视频去除背景工具',
          remarks: '',
          describe: '视频去除背景工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb959',
          name: '老照片无损修复',
          url: 'https://jpghd.com/',
          icon: 'huasen-store/icon/1680283169184.png',
          code: 0,
          expand: '{}',
          description: '人工智能无损修复老旧图片',
          remarks: '',
          describe: '人工智能无损修复老旧图片',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb95a',
          name: '图片无损缩放',
          url: 'https://icons8.com/upscaler',
          icon: 'huasen-store/icon/1666504929143.png',
          code: 0,
          expand: '{}',
          description: '在线提高图像分辨率网站',
          remarks: '',
          describe: '在线提高图像分辨率网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb95b',
          name: '视频转GIF',
          url: 'https://www.apowersoft.cn/video-to-gif-online',
          icon: 'huasen-store/icon/1666500318232.png',
          code: 0,
          expand: '{}',
          description: '在线视频片段转化GIF工具',
          remarks: '',
          describe: '在线视频片段转化GIF工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb95c',
          name: 'Panzoid',
          url: 'https://panzoid.com/',
          icon: 'huasen-store/icon/1666504996436.png',
          code: 0,
          expand: '{}',
          description: '在线制作炫酷视频片头网站',
          remarks: '',
          describe: '在线制作炫酷视频片头网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb95d',
          name: 'Waifu2x',
          url: 'http://waifu2x.udp.jp/',
          icon: 'huasen-store/icon/1671379387356.png',
          code: 0,
          expand: '{}',
          description: '支持动漫风格图片无损放大',
          remarks: '',
          describe: '支持动漫风格图片无损放大',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb95e',
          name: '泼辣修图',
          url: 'https://editor.polaxiong.com/',
          icon: 'huasen-store/icon/1666499305336.png',
          code: 0,
          expand: '{}',
          description: '在线修图调色工具',
          remarks: '',
          describe: '在线修图调色工具',
          remark: '',
        },
      ],
    },
    {
      typeName: '产品·原型',
      sites: [
        {
          _id: '6418821e39ede6001dacb95f',
          name: '人人产品经理',
          url: 'http://www.woshipm.com/',
          icon: 'huasen-store/icon/1666512394984.png',
          code: 0,
          expand: '{}',
          description: '产品爱好者学习交流平台',
          remarks: '',
          describe: '产品爱好者学习交流平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb960',
          name: '产品壹佰',
          url: 'http://www.chanpin100.com/',
          icon: 'huasen-store/icon/1666512434605.png',
          code: 0,
          expand: '{}',
          description: '优质的产品经理学习网站',
          remarks: '',
          describe: '优质的产品经理学习网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb961',
          name: '墨刀',
          url: 'https://modao.cc/brand',
          icon: 'huasen-store/icon/1666512458578.png',
          code: 0,
          expand: '{}',
          description: '产品设计一体化在线协同办公平台',
          remarks: '',
          describe: '产品设计一体化在线协同办公平台',
          remark: '',
        },
      ],
    },
    {
      typeName: '站长·运营',
      sites: [
        {
          _id: '6418821e39ede6001dacb962',
          name: '阿里云',
          url: 'https://www.aliyun.com/',
          icon: 'huasen-store/icon/1666513655353.png',
          code: 0,
          expand: '{}',
          description: '安全稳定的云产品及服务',
          remarks: '',
          describe: '安全稳定的云产品及服务',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb963',
          name: '腾讯云',
          url: 'https://cloud.tencent.com/',
          icon: 'huasen-store/icon/1666513683068.png',
          code: 0,
          expand: '{}',
          description: '为企业和开发者提供安全稳定的云计算服务',
          remarks: '',
          describe: '为企业和开发者提供安全稳定的云计算服务',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb964',
          name: '百度联盟',
          url: 'https://union.baidu.com/',
          icon: 'https://union.baidu.com/bqt/favicon.ico',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '64341eaed38d46021cca31ed',
          name: 'PortChecker',
          url: 'https://coding.tools/cn/port-checker',
          icon: 'huasen-store/icon/1681137273719.png',
          code: 0,
          expand: '{}',
          description: '简洁的端口扫描工具',
          describe: '简洁的端口扫描工具',
        },
        {
          _id: '643cf30f7a20190029baee1c',
          name: 'IP地址查询',
          url: 'https://www.ip.cn/',
          icon: 'huasen-store/icon/1681744505496.png',
          code: 0,
          expand: '{}',
          description: '简洁的ip地址查询网站',
          remarks: '',
          describe: '简洁的ip地址查询网站',
          remark: '',
        },
      ],
    },
    {
      typeName: '生活·消费',
      sites: [
        {
          _id: '6418821e39ede6001dacb965',
          name: '快递100',
          url: 'https://www.kuaidi100.com/',
          icon: 'huasen-store/icon/1680283243394.png',
          code: 0,
          expand: '{}',
          description: '查询快递物流信息',
          remarks: '',
          describe: '查询快递物流信息',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb966',
          name: '邮政业申诉服务平台',
          url: 'https://sswz.spb.gov.cn/index.html',
          icon: 'huasen-store/icon/1671958542475.png',
          code: 0,
          expand: '{}',
          description: '快递公司的不法行为进行投诉',
          remarks: '',
          describe: '快递公司的不法行为进行投诉',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb967',
          name: '12306',
          url: 'https://www.12306.cn/index/',
          icon: 'huasen-store/icon/1666510047987.png',
          code: 0,
          expand: '{}',
          description: '中国铁路出行信息平台',
          remarks: '',
          describe: '中国铁路出行信息平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb968',
          name: '淘宝网',
          url: 'https://www.taobao.com/',
          icon: 'huasen-store/icon/1666510116680.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb969',
          name: '京东商城',
          url: 'https://www.jd.com/',
          icon: 'huasen-store/icon/1666510143904.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb96a',
          name: '美食杰',
          url: 'http://www.meishi.cc/',
          icon: 'huasen-store/icon/1666509656460.png',
          code: 0,
          expand: '{}',
          description: '值得你收藏的美食视频教学网站',
          remarks: '',
          describe: '值得你收藏的美食视频教学网站',
          remark: '',
        },
      ],
    },
    {
      typeName: '办公·资源',
      sites: [
        {
          _id: '642823aed38d46021cca31df',
          name: '第一范文网',
          url: 'https://www.diyifanwen.com/',
          icon: 'huasen-store/icon/1680352083769.png',
          code: 0,
          expand: '{}',
          description: '日常文案写作模版网站',
          describe: '日常文案写作模版网站',
        },
        {
          _id: '641882a639ede6001dacb9b5',
          name: '百字',
          url: 'https://www.100font.com/',
          icon: 'huasen-store/icon/1680354695585.png',
          code: 0,
          expand: '{}',
          description: '专注于收集可商用字体的网站',
          remarks: '',
          describe: '专注于收集可商用字体的网站',
          remark: '',
        },
        {
          _id: '641882a639ede6001dacb9b2',
          name: 'PPT模版',
          url: 'https://www.1ppt.com/',
          icon: 'huasen-store/icon/1680354748738.png',
          code: 0,
          expand: '{}',
          description: '幻灯片背景/模版/素材下载网站',
          remarks: '',
          describe: '幻灯片背景/模版/素材下载网站',
          remark: '',
        },
        {
          _id: '641882a639ede6001dacb9b3',
          name: 'PPT超级市场',
          url: 'https://www.pptsupermarket.com/',
          icon: 'huasen-store/icon/1680354767660.png',
          code: 0,
          expand: '{}',
          description: '优质/高效/安全的PPT模板下载网站',
          remarks: '',
          describe: '优质/高效/安全的PPT模板下载网站',
          remark: '',
        },
        {
          _id: '641882a639ede6001dacb9b4',
          name: '优品PPT',
          url: 'https://www.ypppt.com/',
          icon: 'huasen-store/icon/1666513179967.png',
          code: 0,
          expand: '{}',
          description: '有情怀的免费PPT模板下载网站',
          remarks: '',
          describe: '有情怀的免费PPT模板下载网站',
          remark: '',
        },
        {
          _id: '641882a639ede6001dacb9b6',
          name: '字体转换器',
          url: 'https://www.diyiziti.com/',
          icon: 'huasen-store/icon/1666512882910.png',
          code: 0,
          expand: '{}',
          description: '在线转换书法字体网站',
          remarks: '',
          describe: '在线转换书法字体网站',
          remark: '',
        },
      ],
    },
    {
      typeName: '学习·求职',
      sites: [
        {
          _id: '6418821e39ede6001dacb96b',
          name: '腾讯课堂',
          url: 'https://ke.qq.com/',
          icon: 'huasen-store/icon/1666510234046.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb96c',
          name: '中国慕课',
          url: 'https://www.icourse163.org/',
          icon: 'huasen-store/icon/1666510251306.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb96d',
          name: '网易云课堂',
          url: 'https://study.163.com/',
          icon: 'huasen-store/icon/1666510270226.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb96e',
          name: '公开课',
          url: 'https://open.163.com/',
          icon: 'huasen-store/icon/1666510339327.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb96f',
          name: '极简简历',
          url: 'https://www.polebrief.com/edit',
          icon: 'huasen-store/icon/1666510384500.png',
          code: 0,
          expand: '{}',
          description: '在线制作简历网站',
          remarks: '',
          describe: '在线制作简历网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb970',
          name: '锤子简历',
          url: 'https://www.100chui.com/',
          icon: 'huasen-store/icon/1666510442235.png',
          code: 0,
          expand: '{}',
          description: '模版丰富的简历制作平台',
          remarks: '',
          describe: '模版丰富的简历制作平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb971',
          name: '超级简历',
          url: 'https://www.wondercv.com/',
          icon: 'huasen-store/icon/1666510491667.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb972',
          name: '实习僧',
          url: 'https://www.shixiseng.com/',
          icon: 'huasen-store/icon/1680114260831.png',
          code: 0,
          expand: '{}',
          description: '实习生招聘信息网站',
          remarks: '',
          describe: '实习生招聘信息网站',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb973',
          name: '牛客求职',
          url: 'https://www.nowcoder.com/jobs/recommend/campus',
          icon: 'huasen-store/icon/1666510577314.png',
          code: 0,
          expand: '{}',
          description: '高时效更新校园招聘信息的平台',
          remarks: '',
          describe: '高时效更新校园招聘信息的平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb974',
          name: '拉勾网',
          url: 'https://www.lagou.com/',
          icon: 'huasen-store/icon/1680114315536.png',
          code: 0,
          expand: '{}',
          description: '回复率较高的工作招聘平台',
          remarks: '',
          describe: '回复率较高的工作招聘平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb975',
          name: '应届生求职网',
          url: 'http://www.yingjiesheng.com/',
          icon: 'huasen-store/icon/1680114430785.png',
          code: 0,
          expand: '{}',
          description: '应届生招聘信息发布平台',
          remarks: '',
          describe: '应届生招聘信息发布平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb976',
          name: '丁香人才',
          url: 'https://www.jobmd.cn/',
          icon: 'huasen-store/icon/1666510638935.png',
          code: 0,
          expand: '{}',
          description: '专注于医学生的求职网站',
          remarks: '',
          describe: '专注于医学生的求职网站',
          remark: '',
        },
      ],
    },
    {
      typeName: '知识·科普',
      sites: [
        {
          _id: '6418821e39ede6001dacb977',
          name: '古诗文网',
          url: 'https://www.gushiwen.cn/',
          icon: 'huasen-store/icon/1666511115128.png',
          code: 0,
          expand: '{}',
          description: '古诗文网作为传承经典的网站专注于古诗文服务',
          remarks: '',
          describe: '古诗文网作为传承经典的网站专注于古诗文服务',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb978',
          name: '中国科普博览',
          url: 'http://www.kepu.net.cn/',
          icon: 'huasen-store/icon/1666511155146.png',
          code: 0,
          expand: '{}',
          description: '传播有温度有态度的新科学观',
          remarks: '',
          describe: '传播有温度有态度的新科学观',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb979',
          name: '科学网',
          url: 'https://paper.sciencenet.cn/',
          icon: 'huasen-store/icon/1666511215139.png',
          code: 0,
          expand: '{}',
          description: '丰富实用的科学信息服务以及交流互动的网络平台',
          remarks: '',
          describe: '丰富实用的科学信息服务以及交流互动的网络平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb97a',
          name: '每日一文',
          url: 'https://meiriyiwen.com/',
          icon: 'huasen-store/icon/1671962320225.png',
          code: 0,
          expand: '{}',
          description: '每天静下心来读一篇文章',
          remarks: '',
          describe: '每天静下心来读一篇文章',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb97b',
          name: 'TopBook',
          url: 'https://topbook.cc/',
          icon: 'huasen-store/icon/1671962368682.png',
          code: 0,
          expand: '{}',
          description: '高效生活视频书',
          remarks: '',
          describe: '高效生活视频书',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb97c',
          name: '网易人间',
          url: 'https://renjian.163.com/',
          icon: 'huasen-store/icon/1671975354529.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
    {
      typeName: '专业·导航',
      sites: [
        {
          _id: '6418821e39ede6001dacb97d',
          name: 'Upsort',
          url: 'https://upsort.com/',
          icon: 'huasen-store/icon/1671975538951.png',
          code: 0,
          expand: '{}',
          description: '为您全方位提供财经资讯及全球金融市场行情',
          remarks: '',
          describe: '为您全方位提供财经资讯及全球金融市场行情',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb97e',
          name: '读书全面阅读门户',
          url: 'https://www.dushu.com/',
          icon: 'huasen-store/icon/1671975662944.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb97f',
          name: '科塔学术导航',
          url: 'https://site.sciping.com/',
          icon: 'huasen-store/icon/1680114053589.png',
          code: 0,
          expand: '{}',
          description: '专业准确的全面的科研与学术资源导航平台',
          remarks: '',
          describe: '专业准确的全面的科研与学术资源导航平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb980',
          name: 'Seeseed',
          url: 'https://www.seeseed.com/',
          icon: 'huasen-store/icon/1680114076219.png',
          code: 0,
          expand: '{}',
          description: '美观且优秀的设计专业导航',
          remarks: '',
          describe: '美观且优秀的设计专业导航',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb981',
          name: '法聚导航',
          url: 'https://www.jufadh.com/',
          icon: 'huasen-store/icon/1680114142624.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb982',
          name: '工业自动化导航',
          url: 'https://at.stiny.cn/',
          icon: 'huasen-store/icon/1680114167612.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb983',
          name: '12371',
          url: 'https://www.12371.cn/',
          icon: 'huasen-store/icon/1680114027108.png',
          code: 0,
          expand: '{}',
          description: '共产党员上网助手',
          remarks: '',
          describe: '共产党员上网助手',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb984',
          name: '大木虫考研',
          url: 'http://www.8006.net/',
          icon: 'huasen-store/icon/1680114000101.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
    {
      typeName: '苹果·必备',
      sites: [
        {
          _id: '6418821e39ede6001dacb985',
          name: 'Keka',
          url: 'https://www.keka.io/en/',
          icon: 'huasen-store/icon/1671950066183.png',
          code: 0,
          expand: '{}',
          description: '轻便的解压缩神器',
          remarks: '',
          describe: '轻便的解压缩神器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb986',
          name: 'TextMate',
          url: 'https://macromates.com/',
          icon: 'huasen-store/icon/1671950179618.png',
          code: 0,
          expand: '{}',
          description: '简洁的文本编辑工具',
          remarks: '',
          describe: '简洁的文本编辑工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb987',
          name: 'Movist',
          url: 'https://movist.en.softonic.com/mac',
          icon: 'huasen-store/icon/1666514979416.png',
          code: 0,
          expand: '{}',
          description: '支持各种音频文件的播放器',
          remarks: '',
          describe: '支持各种音频文件的播放器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb988',
          name: 'AdGuard',
          url: 'https://adguard.com/zh_cn/welcome.html',
          icon: 'huasen-store/icon/1666514863712.png',
          code: 0,
          expand: '{}',
          description: '摆脱烦恼的广告屏蔽工具',
          remarks: '',
          describe: '摆脱烦恼的广告屏蔽工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb989',
          name: '多线程下载工具',
          url: 'https://www.freedownloadmanager.org/zh/',
          icon: 'huasen-store/icon/1666514834728.png',
          code: 0,
          expand: '{}',
          description: '支持多线程任务下载工具',
          remarks: '',
          describe: '支持多线程任务下载工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb98a',
          name: 'Mos',
          url: 'https://mos.caldis.me/',
          icon: 'huasen-store/icon/1666514753054.png',
          code: 0,
          expand: '{}',
          description: '鼠标丝滑滚动神器',
          remarks: '',
          describe: '鼠标丝滑滚动神器',
          remark: '',
        },
      ],
    },
    {
      typeName: '苹果·精选',
      sites: [
        {
          _id: '6418821e39ede6001dacb98b',
          name: 'UPic',
          url: 'https://github.com/gee1k/uPic/tags',
          icon: 'huasen-store/icon/1666514881527.png',
          code: 0,
          expand: '{}',
          description: '免费而强大的Mac图床客户端',
          remarks: '',
          describe: '免费而强大的Mac图床客户端',
          remark: '',
        },
      ],
    },
    {
      typeName: '微软·必备',
      sites: [
        {
          _id: '6418821e39ede6001dacb98c',
          name: '7zip',
          url: 'https://www.7-zip.org/',
          icon: 'huasen-store/icon/1666513953189.png',
          code: 0,
          expand: '{}',
          description: '体积小无广告的解压缩工具',
          remarks: '',
          describe: '体积小无广告的解压缩工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb98d',
          name: 'Geek',
          url: 'https://geekuninstaller.pro/',
          icon: 'huasen-store/icon/1666513981156.png',
          code: 0,
          expand: '{}',
          description: '超好用的卸载工具',
          remarks: '',
          describe: '超好用的卸载工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb98e',
          name: 'CCleaner',
          url: 'https://www.ccleaner.com/download',
          icon: 'huasen-store/icon/1666514014668.png',
          code: 0,
          expand: '{}',
          description: '一款强力的垃圾清理软件',
          remarks: '',
          describe: '一款强力的垃圾清理软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb990',
          name: '火绒安全',
          url: 'https://www.huorong.cn/',
          icon: 'huasen-store/icon/1666513931047.png',
          code: 0,
          expand: '{}',
          description: '良心的安全电脑管理软件',
          remarks: '',
          describe: '良心的安全电脑管理软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb991',
          name: '新Edge浏览器',
          url: 'https://www.microsoft.com/zh-cn/edge',
          icon: 'huasen-store/icon/1666514003644.png',
          code: 0,
          expand: '{}',
          description: '功能齐全的小白必备浏览器',
          remarks: '',
          describe: '功能齐全的小白必备浏览器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb992',
          name: 'Everything',
          url: 'https://www.voidtools.com/zh-cn/',
          icon: 'huasen-store/icon/1666514462063.png',
          code: 0,
          expand: '{}',
          description: '支持名称快速定位文件和文件夹',
          remarks: '',
          describe: '支持名称快速定位文件和文件夹',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb993',
          name: 'QuickLook',
          url: 'https://pooi.moe/QuickLook/',
          icon: 'huasen-store/icon/1666514479249.png',
          code: 0,
          expand: '{}',
          description: '支持选择文件后空格预览',
          remarks: '',
          describe: '支持选择文件后空格预览',
          remark: '',
        },
      ],
    },
    {
      typeName: '微软·精选',
      sites: [
        {
          _id: '6418821e39ede6001dacb994',
          name: '系统操作箱',
          url: 'https://www.aliyundrive.com/s/ZJECYtPDzYu',
          icon: 'huasen-store/icon/1666514072032.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb995',
          name: '万彩办公大师',
          url: 'http://www.wofficebox.com/',
          icon: 'huasen-store/icon/1666514178778.png',
          code: 0,
          expand: '{}',
          description: '办公必备的小工具百宝箱',
          remarks: '',
          describe: '办公必备的小工具百宝箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb996',
          name: 'GIF录制工具',
          url: 'https://www.screentogif.com/',
          icon: 'huasen-store/icon/1666514222765.png',
          code: 0,
          expand: '{}',
          description: '好用的GIF图片录屏工具',
          remarks: '',
          describe: '好用的GIF图片录屏工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb997',
          name: 'Todesk',
          url: 'https://www.todesk.com/',
          icon: 'huasen-store/icon/1666514099886.png',
          code: 0,
          expand: '{}',
          description: '远程操控软件',
          remarks: '',
          describe: '远程操控软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb998',
          name: '多译',
          url: 'https://duoyiapp.com/',
          icon: 'huasen-store/icon/1681626602691.png',
          code: 0,
          expand: '{}',
          description: '快速提升翻译效率',
          remarks: '',
          describe: '快速提升翻译效率',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb999',
          name: '全局鼠标手势',
          url: 'https://www.yingdev.com/projects/wgestures',
          icon: 'huasen-store/icon/1681626625944.png',
          code: 0,
          expand: '{}',
          description: '鼠标手势控制软件',
          remarks: '',
          describe: '鼠标手势控制软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb99a',
          name: '讯飞语记',
          url: 'https://iflynote.com/',
          icon: 'huasen-store/icon/1681626653066.png',
          code: 0,
          expand: '{}',
          description: '支持实时语音识别软件',
          remarks: '',
          describe: '支持实时语音识别软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb99b',
          name: '洋芋图像工具箱',
          url: 'https://www.potatofield.cn/imagetoolkit/',
          icon: 'huasen-store/icon/1666514307844.png',
          code: 0,
          expand: '{}',
          description: '一个适用于创意行业从业者的图像工具箱',
          remarks: '',
          describe: '一个适用于创意行业从业者的图像工具箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb99c',
          name: '优效日历',
          url: 'http://www.youxiao.cn/',
          icon: 'huasen-store/icon/1666514336481.png',
          code: 0,
          expand: '{}',
          description: '界面简洁的桌面日历软件',
          remarks: '',
          describe: '界面简洁的桌面日历软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb99d',
          name: '小黄条',
          url: 'https://www.yynote.cn/',
          icon: 'huasen-store/icon/1666514508760.png',
          code: 0,
          expand: '{}',
          description: '桌面便签/任务清单/备忘录的效率工具',
          remarks: '',
          describe: '桌面便签/任务清单/备忘录的效率工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb99e',
          name: 'Quicker',
          url: 'https://getquicker.net/',
          icon: 'huasen-store/icon/1666514536602.png',
          code: 0,
          expand: '{}',
          description: '鼠标党的指尖工具箱',
          remarks: '',
          describe: '鼠标党的指尖工具箱',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb99f',
          name: '录屏神器',
          url: 'https://www.aliyundrive.com/s/tK32yFZG85u',
          icon: 'huasen-store/icon/1666514562835.png',
          code: 0,
          expand: '{}',
          description: '十分好用的录屏工具',
          remarks: '',
          describe: '十分好用的录屏工具',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a0',
          name: 'UTool',
          url: 'https://u.tools/',
          icon: 'huasen-store/icon/1666514611775.png',
          code: 0,
          expand: '{}',
          description: '键盘党的自由组合工具集',
          remarks: '',
          describe: '键盘党的自由组合工具集',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a1',
          name: 'DeskGo',
          url: 'https://guanjia.qq.com/product/zmzl/',
          icon: 'huasen-store/icon/1666515007079.png',
          code: 0,
          expand: '{}',
          description: '桌面整理收纳工具（下载独立版）',
          remarks: '',
          describe: '桌面整理收纳工具（下载独立版）',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a2',
          name: 'PicGo',
          url: 'https://molunerfinn.com/PicGo/',
          icon: 'huasen-store/icon/1666514673440.png',
          code: 0,
          expand: '{}',
          description: '开源/免费/功能强大的图床软件',
          remarks: '',
          describe: '开源/免费/功能强大的图床软件',
          remark: '',
        },
      ],
    },
    {
      typeName: '通用·兼容',
      sites: [
        {
          _id: '6418821e39ede6001dacb98f',
          name: 'Snipaste',
          url: 'https://zh.snipaste.com/',
          icon: 'huasen-store/icon/1666514355988.png',
          code: 0,
          expand: '{}',
          description: '截图神器',
          remarks: '',
          describe: '截图神器',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a4',
          name: 'Landrop',
          url: 'https://landrop.app/',
          icon: 'huasen-store/icon/1671950394031.png',
          code: 0,
          expand: '{}',
          description: '多平台局域网文件传输文件网站',
          remarks: '',
          describe: '多平台局域网文件传输文件网站',
          remark: '',
        },
        {
          _id: '643817c87e3359006cbdbc88',
          name: '图吧工具箱',
          url: 'http://www.tbtool.cn/',
          icon: 'huasen-store/icon/1681397685077.png',
          code: 0,
          expand: '{}',
          description: 'DIY爱好者的必备工具合集',
          describe: 'DIY爱好者的必备工具合集',
        },
      ],
    },
    {
      typeName: '软件·市场',
      sites: [
        {
          _id: '6418821e39ede6001dacb9a5',
          name: '数码荔枝',
          url: 'https://store.lizhi.io/',
          icon: 'huasen-store/icon/1671290205692.png',
          code: 0,
          expand: '{}',
          description: '专注于分享优秀的正版软件',
          remarks: '',
          describe: '专注于分享优秀的正版软件',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a6',
          name: '马可菠萝',
          url: 'https://www.macbl.com/',
          icon: 'huasen-store/icon/1666514728680.png',
          code: 0,
          expand: '{}',
          description: '苹果软件推荐下载平台',
          remarks: '',
          describe: '苹果软件推荐下载平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a7',
          name: 'Appstorrent',
          url: 'https://appstorrent.ru/',
          icon: 'huasen-store/icon/1671332291090.png',
          code: 0,
          expand: '{}',
          description: '国外资源丰富的MAC软件下载平台',
          remarks: '',
          describe: '国外资源丰富的MAC软件下载平台',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a8',
          name: '麦氪派',
          url: 'https://www.waitsun.com/topics/os',
          icon: 'huasen-store/icon/1671963156944.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9a9',
          name: 'Torrentmac',
          url: 'https://www.torrentmac.net/',
          icon: '',
          code: 0,
          expand: '{}',
          description: '免费的Mac资源下载的外网站点',
          remarks: '',
          describe: '免费的Mac资源下载的外网站点',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9aa',
          name: '奇迹秀工具箱',
          url: 'https://www.qijishow.com/down/tools.html',
          icon: 'huasen-store/icon/1671954967355.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
    {
      typeName: '天梯·榜单',
      sites: [
        {
          _id: '6418821e39ede6001dacb9ab',
          name: 'CPU天梯榜',
          url: 'https://topic.expreview.com/CPU/',
          icon: 'huasen-store/icon/1680283409025.png',
          code: 0,
          expand: '{}',
          description: 'CPU版本参数天梯榜',
          remarks: '',
          describe: 'CPU版本参数天梯榜',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9ac',
          name: '显卡天梯榜',
          url: 'https://topic.expreview.com/GPU/',
          icon: 'huasen-store/icon/1680283427858.png',
          code: 0,
          expand: '{}',
          description: '显卡参数性能天梯榜',
          remarks: '',
          describe: '显卡参数性能天梯榜',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9ad',
          name: '电源天梯榜',
          url: 'https://topic.expreview.com/Power/',
          icon: 'huasen-store/icon/1680283451062.png',
          code: 0,
          expand: '{}',
          description: '电源性能排行榜单',
          remarks: '',
          describe: '电源性能排行榜单',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9ae',
          name: '猫眼电影票房榜',
          url: 'https://piaofang.maoyan.com/dashboard',
          icon: 'huasen-store/icon/1680194879528.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
        {
          _id: '6418821e39ede6001dacb9af',
          name: 'TapTap游戏榜',
          url: 'https://www.taptap.cn/top/played',
          icon: 'huasen-store/icon/1680194904225.png',
          code: 0,
          expand: '{}',
          description: '',
          remarks: '',
          describe: '',
          remark: '',
        },
      ],
    },
  ],
});

export default {
  findJournal,
  findJournalInformationById,
};
